# Generated by Django 3.2.2 on 2021-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('date_create', models.DateField(default='2021-05-10 13:16')),
                ('review_date', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('review_id', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
