# Generated by Django 3.2.2 on 2021-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='text',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_create',
            field=models.DateTimeField(default='2021-06-05 16:25'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_modified',
            field=models.DateTimeField(default='2021-06-05 16:25'),
        ),
    ]
